import Foundation
import Security

struct CertificateRecord: Codable, Identifiable, Equatable {
    let id: UUID
    let filename: String
    let commonName: String?
    let organization: String?
    let teamID: String?
    let notAfter: Date?
    let certificateSHA256: String?
    let addedAt: Date
    var hasSavedPassword: Bool

    var displayName: String { commonName ?? filename }
}

/// Remembers imported signing certificates on-device (Application Support)
/// and optionally their passwords in the Keychain.
@MainActor
final class CertificateStore: ObservableObject {
    @Published private(set) var certificates: [CertificateRecord] = []
    @Published var selectedID: UUID?
    @Published var pendingImportURL: URL?

    private let dir: URL
    private let indexURL: URL

    private struct Index: Codable {
        var certificates: [CertificateRecord] = []
        var selectedID: UUID?
    }

    init() {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        dir = base.appendingPathComponent("Certificates", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        indexURL = base.appendingPathComponent("certificates.json")
        load()
        removeLegacyPasswordFiles()
    }

    var selected: CertificateRecord? {
        certificates.first { $0.id == selectedID }
    }

    func fileURL(for record: CertificateRecord) -> URL {
        dir.appendingPathComponent(record.filename)
    }

    func savedPassword(for record: CertificateRecord) -> String? {
        PasswordVault.password(for: record.id)
    }

    enum ImportError: LocalizedError {
        case unreadable
        case badPassword
        case copyFailed

        var errorDescription: String? {
            switch self {
            case .unreadable: return "The file could not be read."
            case .badPassword: return "Wrong password, or not a valid signing certificate."
            case .copyFailed: return "The certificate could not be saved, or its password could not be stored securely."
            }
        }
    }

    /// Validates the p12 against the password, stores it on-device and selects it.
    @discardableResult
    func importCertificate(from source: URL, password: String, rememberPassword: Bool)
        -> Result<CertificateRecord, ImportError> {
        let scoped = source.startAccessingSecurityScopedResource()
        defer { if scoped { source.stopAccessingSecurityScopedResource() } }

        guard let data = try? Data(contentsOf: source) else { return .failure(.unreadable) }

        var filename = source.lastPathComponent
        if certificates.contains(where: { $0.filename == filename }) {
            let stem = source.deletingPathExtension().lastPathComponent
            let short = UUID().uuidString.prefix(6)
            filename = "\(stem)-\(short).\(source.pathExtension)"
        }

        let dest = dir.appendingPathComponent(filename)
        do {
            try data.write(to: dest, options: .completeFileProtection)
        } catch {
            return .failure(.copyFailed)
        }

        guard let info = P12Inspector.inspect(url: dest, password: password) else {
            try? FileManager.default.removeItem(at: dest)
            return .failure(.badPassword)
        }

        var record = CertificateRecord(
            id: UUID(),
            filename: filename,
            commonName: info.commonName,
            organization: info.organization,
            teamID: info.teamID,
            notAfter: info.notAfter,
            certificateSHA256: info.certificateSHA256,
            addedAt: .now,
            hasSavedPassword: false
        )

        if rememberPassword {
            guard PasswordVault.save(password, for: record.id) else {
                try? FileManager.default.removeItem(at: dest)
                return .failure(.copyFailed)
            }
            record.hasSavedPassword = true
        }

        certificates.append(record)
        selectedID = record.id
        save()
        return .success(record)
    }

    /// Imports a certificate generated by an on-device provisioning provider.
    /// Existing records with the same certificate fingerprint are reused.
    @discardableResult
    func importCertificate(data: Data,
                           suggestedFilename: String,
                           password: String,
                           rememberPassword: Bool) -> Result<CertificateRecord, ImportError> {
        let safeName = URL(fileURLWithPath: suggestedFilename).lastPathComponent
        let filename = safeName.lowercased().hasSuffix(".p12") ? safeName : "\(safeName).p12"
        let temporaryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("forgesign-\(UUID().uuidString)-\(filename)")
        do {
            try data.write(to: temporaryURL, options: [.atomic, .completeFileProtection])
        } catch {
            return .failure(.copyFailed)
        }
        defer { try? FileManager.default.removeItem(at: temporaryURL) }

        guard let info = P12Inspector.inspect(url: temporaryURL, password: password) else {
            return .failure(.badPassword)
        }
        if let fingerprint = info.certificateSHA256,
           let existing = certificates.first(where: {
               $0.certificateSHA256?.caseInsensitiveCompare(fingerprint) == .orderedSame
           }) {
            if rememberPassword && !PasswordVault.save(password, for: existing.id) {
                return .failure(.copyFailed)
            }
            selectedID = existing.id
            if rememberPassword, let index = certificates.firstIndex(where: { $0.id == existing.id }) {
                certificates[index].hasSavedPassword = true
            }
            save()
            return .success(certificates.first(where: { $0.id == existing.id }) ?? existing)
        }
        return importCertificate(from: temporaryURL, password: password, rememberPassword: rememberPassword)
    }

    func delete(_ record: CertificateRecord) {
        PasswordVault.delete(for: record.id)
        try? FileManager.default.removeItem(at: fileURL(for: record))
        certificates.removeAll { $0.id == record.id }
        if selectedID == record.id {
            selectedID = certificates.first?.id
        }
        save()
    }

    private func load() {
        guard let data = try? Data(contentsOf: indexURL),
              let index = try? JSONDecoder().decode(Index.self, from: data) else { return }
        certificates = index.certificates.filter { FileManager.default.fileExists(atPath: fileURL(for: $0).path) }
        selectedID = index.selectedID
        if selectedID == nil { selectedID = certificates.first?.id }
    }

    private func save() {
        let index = Index(certificates: certificates, selectedID: selectedID)
        if let data = try? JSONEncoder().encode(index) {
            try? ProtectedPersistence.write(data, to: indexURL)
        }
    }

    private func removeLegacyPasswordFiles() {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        try? FileManager.default.removeItem(at: base.appendingPathComponent("PassVault", isDirectory: true))
    }
}

/// Passwords for remembered certificates. Passwords are kept only in the
/// device-bound Keychain; when Keychain storage is unavailable, remembering is
/// refused and the password must remain in memory for the current signing pass.
enum PasswordVault {
    private static let service = "com.forgesign.mobile.p12"

    static func save(_ password: String, for id: UUID) -> Bool {
        delete(for: id)
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: id.uuidString,
            kSecAttrAccessible as String: kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
            kSecValueData as String: Data(password.utf8)
        ]
        return SecItemAdd(query as CFDictionary, nil) == errSecSuccess
    }

    static func password(for id: UUID) -> String? {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: id.uuidString,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne
        ]
        var item: CFTypeRef?
        guard SecItemCopyMatching(query as CFDictionary, &item) == errSecSuccess,
              let data = item as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    static func delete(for id: UUID) {
        let query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: id.uuidString
        ]
        SecItemDelete(query as CFDictionary)
        let legacyDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("PassVault", isDirectory: true)
        try? FileManager.default.removeItem(at: legacyDir.appendingPathComponent(id.uuidString))
    }
}
